version: '3'
services:
  server:
    env_file: .env
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: tsc/api:0.0.1
    volumes:
      - .:/code
    ports:
      - "8020:8000"
#    external_links:
#     - psql-11-sakchyam_db:db
