# Generated by Django 2.0.3 on 2018-04-06 15:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_properties', django.contrib.postgres.fields.jsonb.JSONField()),
                ('phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('call_type', models.SmallIntegerField(choices=[(1, 'Query'), (2, 'Complain')], default=1)),
                ('other_properties', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('CSR', 'CSR'), ('Moderator', 'Moderator'), ('Superuser', 'Superuser')], default='CSR', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calldetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_detail', to='core.Category'),
        ),
        migrations.AddField(
            model_name='calldetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
