# Generated by Django 2.0.4 on 2018-04-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180412_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_district',
            field=models.BooleanField(default=True),
        ),
    ]
