# Generated by Django 2.0.4 on 2018-04-22 15:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_has_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='has_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='calldetail',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_detail', to='core.TypeOption'),
        ),
    ]
