# Generated by Django 2.0.4 on 2018-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180422_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='call_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
