# Generated by Django 2.0.4 on 2018-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180531_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetail',
            name='call_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calldetail',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
